### ISSUE TITLE
math is wrong, 2+2=3, 3+3=4

### ISSUE THREAD

**Issue by livibetter** [zacariaz/c2048#2]
Somehow this game redefines additions.

**Comment by zacariaz** [comment]
AH, I see how that may be confusing, but it's quite simple. We're talking power of 2, i.e. 2^1 = 2, 2^2 = 4, 2^3 = 8, etc.

I'll be sure to add an explanation somewhere.

**Comment by livibetter** [comment]
@zacariaz Have you played other 2048 clones? I have never seen any clone doing this way.

**Comment by zacariaz** [comment]
@livibetter I suppose not, but it's really the same, the look is just different, and it help a whole lot making things actually fit on the screen, only to have to worry about two digit instead of potentially 6, or even 7, if you include a separator.

You will notice of course that your score is calculated correctly, so there's really no difference worth mentioning.

**Comment by livibetter** [comment]
inb4 duplicate issue.
